USE ROLE ACCOUNTADMIN; 

-- creating a warehouse
CREATE WAREHOUSE TRANSFORMING WITH WAREHOUSE_SIZE = 'XSMALL';

CREATE DATABASE RETAIL_PROD COMMENT = 'retail production database';
CREATE SCHEMA "RETAIL_PROD"."RAW" COMMENT = 'raw form data';
CREATE SCHEMA "RETAIL_PROD"."ANALYTICS" COMMENT = 'processed data';


CREATE DATABASE RETAIL_DEV CLONE PROD;

-- access role
CREATE ROLE TRANSFORMER COMMENT = 'role for retial_prod';
CREATE ROLE TRANSFORMER_DEV COMMENT = 'role for dbt';


CREATE USER PROD_TEAM PASSWORD='prod' DEFAULT_ROLE = TRANSFORMER MUST_CHANGE_PASSWORD = true;
GRANT ROLE TRANSFORMER TO USER PROD_TEAM;


GRANT USAGE,OPERATE ON WAREHOUSE TRANSFORMING TO ROLE TRANSFORMER;
GRANT USAGE,CREATE SCHEMA ON DATABASE PROD TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA "RETAIL_PROD"."RAW" TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA "RETAIL_PROD"."ANALYTICS" TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA "RETAIL_PROD"."RAW" TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA "RETAIL_PROD"."RAW" TO ROLE TRANSFORMER;


CREATE USER DEV_TEAM PASSWORD='dev' DEFAULT_ROLE = TRANSFORMER_DEV MUST_CHANGE_PASSWORD = true;
GRANT ROLE TRANSFORMER_DEV TO USER DEV_TEAM;

GRANT USAGE,OPERATE ON WAREHOUSE TRANSFORMING_DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE,CREATE SCHEMA ON DATABASE DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE ON SCHEMA "RETAIL_DEV"."RAW" TO ROLE TRANSFORMER_DEV;
GRANT ALL ON SCHEMA "RETAIL_DEV"."ANALYTICS" TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON ALL TABLES IN SCHEMA "RETAIL_DEV"."RAW" TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA "RETAIL_DEV"."RAW" TO ROLE TRANSFORMER_DEV;





